import java.io.FileNotFoundException;
import java.io.File;
import java.util.ArrayList;
import java.util.Random;
import java.util.Scanner;

public class Games {

    //PRE:  accepts scanner from main
    //POST: asks the user for a 2 digit # & compares the
    //      value to one generated by computer
    //      evaluates whether the user 'won' the lottery
   
    public static void rockpaperscissors(Scanner input) {
        System.out.println("\nWelcome to Rock, Paper, Scissors!!\n");

        // Create random number generator and scanner
        Random rand = new Random();

        // Step 1: Get prompt from player
        System.out.print("Enter (0) Rock, (1) Paper, or (2) Scissors:");
        int playerguess = input.nextInt();
        input.nextLine();
        
        //         

        // Step 2: Ensure number is valid
        while (playerguess != 0 && playerguess != 1 && playerguess != 2) {
            System.out.println("Invalid input. Please enter valid input");
            playerguess = input.nextInt();
            input.nextLine();
        }
        if (playerguess == 0) {
            System.out.println("You chose Rock");
        } else if (playerguess == 1) {
            System.out.println("You chose Paper");
        } else if (playerguess == 2) {
            System.out.println("You chose Scissors");
        }

        // Step 3:Generate a random number for the computer's choice
        int computerGuess = rand.nextInt(3);
        if (computerGuess == 0) {
            System.out.println("Computer chose Rock");
        } else if (computerGuess == 1) {
            System.out.println("Computer chose Paper");
        } else if (computerGuess == 2) {
            System.out.println("Computer chose Scissors");
        }
 
        // Step 4: Game Logic: Compare the player's choice to the computer's choice and determine the winner
        if (playerguess == computerGuess) {
            System.out.println("It's a tie!");
        } else if ((playerguess == 0 && computerGuess == 2) || (playerguess == 1 && computerGuess == 0) || (playerguess == 2 && computerGuess == 1)) {
            System.out.println("You win!");
        } else if ((playerguess == 0 && computerGuess == 1) || (playerguess == 1 && computerGuess == 2) || (playerguess == 2 && computerGuess == 0)) {
            System.out.println("Computer wins!");
        }
        System.out.println("Thanks for playing!");
    }

    //PRE:  accepts scanner from main
    //POST: while the user chooses to play:
    //      the user will place their bet & roll dice
    //      the game will determine the outcome and update the bet
    //      the user cannot play anymore if they are out of money

    public static void scraps(Scanner input) {
        System.out.println("\nWelcome to Scraps!!\n");
        int dice1 = 1 + (int) (Math.random() * 8);
        int dice2 = 1 + (int) (Math.random() * 8);
        int dice3 = 1 + (int) (Math.random() * 8);
        int total = dice1 + dice2 + dice3;

        if (dice1 == 8 || dice2 == 8 || dice3 == 8) {
            System.out.println("You rolled an 8! You win!");
        } else if (total == 9 || total == 10 || total == 14) {
            System.out.println("You rolled a " + total + ". You win!");
        } else if (dice1 == 1 || dice2 == 1 || dice3 == 1) {
            System.out.println("You rolled a 1! You lose!");
        } else if (total == 8 || total == 20 || total == 23 || total == 24) {
            System.out.println("You rolled a " + total + ". You lose!");
        } else {
            int point = total;
            while (true) {
                System.out.println("You rolled a " + total + ". You are in point. Roll again.");
                dice1 = 1 + (int) (Math.random() * 8);
                dice2 = 1 + (int) (Math.random() * 8);
                dice3 = 1 + (int) (Math.random() * 8);
                total = dice1 + dice2 + dice3;
                if (point == total) {
                    System.out.println("You rolled a " + total + ". You win!");
                    break;
                } else if (total == 15) {
                    System.out.println("You rolled a 15! You lose!");
                    break;
                } else if ((dice1 == 8 && dice2 != 8 && dice3 != 8) || (dice1 != 8 && dice2 == 8 && dice3 != 8) || (dice1 != 8 && dice2 != 8 && dice3 == 8)) {
                    System.out.println("You rolled one 8! You lose!");
                    break;
                }
            }
        }

        System.out.println("Thanks for playing!");

    }

    public static void blackjack(Scanner input) {
        System.out.println("Welcome to Blackjack!!");
        String [] suits = {"Hearts", "Diamonds", "Clubs", "Spades"};
        String [] cards = {"A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "Jack", "Queen", "King"};
        String [] deck = new String[52];
        ArrayList<String> playerHand = new ArrayList<>();
        ArrayList<String> dealerHand = new ArrayList<>();
        
        //For loop to create the deck of cards; Used Google gemini to assit in loop creation
        for (int i = 0; i < suits.length; i++) {
            for (int j = 0; j < cards.length; j++) {
                deck[i * cards.length + j] = cards[j] + " of " + suits[i];
                }
            }

        shuffleDeck(deck);
        dealCards(deck, playerHand, dealerHand);
        while (true) {
            System.out.println("Your hand: " + playerHand + " (Value: " + calculateHandValue(playerHand) + ")");
            System.out.println("Dealer's hand: [" + dealerHand.get(0) + ", Hidden]");
            if (calculateHandValue(playerHand) == 21) {
                System.out.println("Blackjack! You win!");
                return;
            }
            if (calculateHandValue(dealerHand) == 21) {
                System.out.println("Dealer has Blackjack! Dealer wins.");
                return;
            }
            System.out.print("Do you want to (H)it or (S)tand? ");
            String choice = input.nextLine().toUpperCase();
            if (choice.equals("H")) {
                playerHand.add(deck[playerHand.size()]);
                if (calculateHandValue(playerHand) > 21) {
                    System.out.println("You bust! Dealer wins.");
                    return;
                } else if (calculateHandValue(playerHand) == 21) {
                    System.out.println("You have 21! You win!");
                    return;
                }
            } else if (choice.equals("S")) {
                System.out.println("Dealer's hand: " + dealerHand + " (Value: " + calculateHandValue(dealerHand) + ")");
                while (calculateHandValue(dealerHand) < calculateHandValue(playerHand) && calculateHandValue(dealerHand) < 21) {
                    dealcard(deck, dealerHand);
                    System.out.println("Dealer's hand: " + dealerHand + " (Value: " + calculateHandValue(dealerHand) + ")");
                }
                    if (calculateHandValue(dealerHand) > 21) {
                        System.out.println("Dealer busts! You win!");
                }   else if (calculateHandValue(playerHand) > calculateHandValue(dealerHand)) {
                        System.out.println("You win!");
                }   else if (calculateHandValue(playerHand) < calculateHandValue(dealerHand)) {
                        System.out.println("Dealer wins.");
                }   else {
                        System.out.println("It's a tie!");
                }
                return;
            } else {
                System.out.println("Invalid input. Please enter H or S.");
            }
        }
    }
    //Method to shuffle deck of cards; Used Google Gemini to assist in method creation
    public static void shuffleDeck(String[] deck) {
        Random rand = new Random();
        for (int i = deck.length - 1; i > 0; i--) {
            int j = rand.nextInt(i + 1);
            String temp = deck[i];
            deck[i] = deck[j];
            deck[j] = temp;
        }
    }
    //Method to deal cards to player and dealer
    public static void dealCards(String[] deck, ArrayList<String> playerHand, ArrayList<String> dealerHand) {
        for (int i = 0; i < 2; i++) {
            playerHand.add(deck[i]);
            dealerHand.add(deck[i + 2]);
            System.out.println("Dealt " + deck[i] + " to player.");
            System.out.println(i == 0 ? "Dealt " + deck[i + 2] + " to dealer." : "Dealt [Hidden] to dealer.");
        }
    }
    //Method to deal a card to one hand
    public static void dealcard(String[] deck, ArrayList<String> hand) {
        hand.add(deck[hand.size()]);
    }
    //Method to calculate the value of a hand
    public static int calculateHandValue(ArrayList<String> hand) {
        int value = 0;
        int aceCount = 0;
        for (String card : hand) {
            String rank = card.split(" ")[0];
            if (rank.equals("A")) {
                value += 11;
                aceCount++;
            } else if (rank.equals("Jack") || rank.equals("Queen") || rank.equals("King")) {
                value += 10;
            } else {
                value += Integer.parseInt(rank);
            }
        }
        // Adjust for aces if value is over 21
        while (value > 21 && aceCount > 0) {
            value -= 10;
            aceCount--;
        }
        return value;
    }

    public static void hangman(Scanner input){
        System.out.println("Welcome to Hangman");
        ArrayList<String> wordList = new ArrayList<>();
        try {
            File file = new File("wordList.txt");
            Scanner scanner = new Scanner(file);
            while (scanner.hasNext()) {
                wordList.add(scanner.next());
            }
            scanner.close();
        } catch (FileNotFoundException e) {
            System.out.println("Error: File not found.");
        }
        String word = getRandom(wordList);
        int guessCount = 6;
        ArrayList<String> guessedLetters = new ArrayList<>();
        char[] maskedWord = new char[word.length()];
        for (int i = 0; i < maskedWord.length; i++) {
            maskedWord[i] = '?';
        }
        while (new String(maskedWord).contains("?") && guessCount > 0) {
            System.out.println("You have " + guessCount + " guesses left.");
            System.out.println("Guessed letters: " + guessedLetters);
            System.out.println("Please guess a letter: ");
            displayMaskedWord(maskedWord);
            String guess = input.nextLine().toLowerCase();
            if (!guessedLetters.contains(guess)) {
                guessedLetters.add(guess);
                boolean correctGuess = false;
                for (int i = 0; i < word.length(); i++) {
                    if (word.charAt(i) == guess.charAt(0)) {
                        maskedWord[i] = guess.charAt(0);
                        correctGuess = true;
                    }
                }
                if (!correctGuess) {
                    System.out.println("Incorrect guess.");
                    guessCount--;
    if (guessCount == 0) {
        System.out.println("You have run out of guesses. The word was: " + word);
    }
    else if (!new String(maskedWord).contains("?")) {
        System.out.println("Congratulations! You guessed the word: " + word);
        }
                }
            }
        }
    }
    public static void displayMaskedWord(char[] maskedWord) {
        for (char c : maskedWord) {
            System.out.print(c + " ");
        }
        System.out.println();
    }

    public static String getRandom(ArrayList<String> wordList) {
        Random random = new Random();
        int randomIndex = random.nextInt(wordList.size());
        return wordList.get(randomIndex);
    }
}


